version: 3.1
services:
  node-todo:
    build: .
    container_name: node-todo
    hostname: node-todo
    ports:
      - 8095:8080/tcp
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    hostname: mongodb
    container_name: dbserver
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME: nodeuser
      - MONGO_INITDB_ROOT_PASSWORD: 'nodepassword'
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod --smallfiles --logpath=/dev/null


