version: '3'

services:
  
  mongo:
    image: mongo:3.4.9
    volumes: 
      - ~/data:/data/db
    command: mongod --smallfiles
    ports:
      - '27017:27017'
  
  node-todo:
    build:
      context: .
    volumes: 
      - ./:/app
    ports: ["8000:8000"]
    depends_on:
      - mongo
