version: '3'

services:
  
  mongo:
    image: mongo:3.4.9
    command: mongod --smallfiles
    ports:
      - '27017:27017'
  
  node-todo:
    image: node:8.5.0
    volumes: 
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c 'npm install;export NODE_ENV=prod; node server.js'
    ports: ["8080:8080"]
    depends_on:
      - mongo
