version: '3'

services:
  
  mongo:
    image: mongo:3.4.9
    command: mongod --smallfiles
    ports:
      - '27017:27017'
  
  node-todo:
    image: node:8.5.0
    volumes: 
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c 'npm install -g nodemon; npm install; npm start; nodemon --debug=5858'
    ports:
      - "8000:8000"
      - "5858:5858"
    depends_on:
      - mongo
