version: '3'

services:
  
  mongo:
    image: mongo:3.4.9
    command: mongod --smallfiles
    ports:
      - '27017:27017'
  
  node-todo:
    image: node:8.5.0
    volumes: 
      - ./:/app
    working_dir: /app
    command: sh -c 'npm install; export NODE_ENV=prod; npm start'
    ports: ["8000:8000"]
    depends_on:
      - mongo
