--
apiVersion: v1
kind: Service
metadata:
  name: todo-service
  labels:
    name: node-todo-service
    app: nodeapp
spec:
  selector:
    name: node-todo
    app: todoapp
  ports:
  - port: 80
    name: node-port
    targetPort: 8080

---
apiVersion: v1
kind: Pod
metadata:
  name: todo-pod
  labels:
    name: node-todo
    app: todoapp
spec:
  containers:
  - name: nodecontainer
  build: .
  ports:
  - containerPort: 8080
--
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    name: mongodb-service
    app: database
spec:
  selector:
    nname: mongodb
    app: database
  ports:
  - port: 27017
    name: db-port
    targetPort: 27017

---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: mongodb
    app: database
spec:
  containers:
  - name: dbcontainer
  image: mongo:4.0.2
  ports:
  - containerPort: 27017