apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    provider: mongodb
    heritage: bitnami
spec:
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongodb
  selector:
    provider: mongodb
