apiVersion: v1
kind: Service
metadata:
  name: node-todo
  labels:
    provider: node-todo
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    provider: node-todo
